apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  labels:
    app: airflow
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    app: airflow
