{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER={{ .Values.minio.rootUser | default "minioadmin" }}
    export MINIO_ROOT_PASSWORD={{ .Values.minio.rootPassword | default "minioadmin" }}
    export MINIO_BROWSER=on
    export MINIO_CONSOLE_ADDRESS=:9001
    export MINIO_SERVER_URL=http://minio-hl:9000
    export MINIO_BROWSER_REDIRECT_URL=http://minio.open-lake.local
    export MINIO_IDENTITY_OPENID_DISPLAY_NAME="Login with Keycloak"
    export MINIO_IDENTITY_OPENID_CONFIG_URL={{ .Values.minio.oidc.configUrl }}
    export MINIO_IDENTITY_OPENID_CLIENT_ID={{ .Values.minio.oidc.clientId }}
    export MINIO_IDENTITY_OPENID_CLIENT_SECRET={{ .Values.minio.oidc.clientSecret }}
    export MINIO_IDENTITY_OPENID_CLAIM_NAME={{ .Values.minio.oidc.claimName | default "policy" }}
    export MINIO_IDENTITY_OPENID_SCOPES={{ .Values.minio.oidc.scopes | default "openid,profile,email" }}
    export MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=on
    export MINIO_IDENTITY_OPENID_VENDOR=keycloak
    export MINIO_IDENTITY_OPENID_KEYCLOAK_REALM={{ .Values.minio.oidc.keycloakRealm | default "open-lake" }}
    export MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL={{ .Values.minio.oidc.keycloakAdminUrl | default "http://security-stack-keycloak/" }}
{{- end }}
