apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "control-panel.fullname" . }}
  labels:
    {{- include "control-panel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "control-panel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "control-panel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "control-panel.serviceAccountName" . }}
      hostAliases:
        - ip: "10.108.86.113" # Keycloak ClusterIP
          hostnames:
            - "keycloak.aetherlake.local"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NEXTAUTH_URL
              value: {{ .Values.nextauth.url | quote }}
            - name: NEXTAUTH_SECRET
              value: {{ .Values.nextauth.secret | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.global.oidc.clientId | quote }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret }}
                  key: control-panel-oidc-secret
            - name: KEYCLOAK_URL
              value: {{ .Values.global.oidc.url | quote }}
            - name: POLARIS_URL
              value: {{ .Values.global.polaris.url | quote }}
            - name: TRINO_URL
              value: "http://core-data-stack-trino.aetherlake.svc.cluster.local:8080"
            - name: POLARIS_CLIENT_ID
              value: "aetherlake-admin"
            - name: POLARIS_CLIENT_SECRET
              value: "aetherlake-secret"
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
